version: '3.4'

networks:
  presentation.api:

services:

  ApplicationDB:
   networks:
    - presentation.api
   container_name: App-Db
   ports:
    - 1401:1433 
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=YourNewStrong@Passw0rd
  
  presentation.api:
    container_name: App-Api
    networks:
     - presentation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8005:80"
      - "8006:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
     - ApplicationDB