version: '3.4'

services:
  ApplicationDB:
   image: mcr.microsoft.com/mssql/server:2019-latest

  presentation.api:
    image: ${DOCKER_REGISTRY-}presentationapi
    build:
      context: .
      dockerfile: Presentation.API/Dockerfile
